---
title: "DATA2002_Report"
date: "`r Sys.Date()`"
author: "500633434"
output: 
  html_document: 
    self_contained: true # Creates a single HTML file as output
    code_folding: hide # Code folding; allows you to show/hide code chunks
    code_download: true # Includes a menu to download the code file
    toc: true # (Optional) Creates a table of contents!
    toc_float: true # table of contents at the side
    number_sections: true # (Optional) Puts numbers next to heading/subheadings
---

```{r}
install.packages("tidyverse")
install.packages("gt")
install.packages("pwr")
install.packages("visdat")
install.packages("janitor")
```


```{r}
library(tidyverse)
x = readr::read_tsv("C:/Users/cyk03/Desktop/data2002/lab/DATA2002asm1/DATA2x02 survey (2022) - Form responses 1 (1).tsv")
```
```{r}
old_names = colnames(x)
```

```{r}
new_names = c("timestamp","covid_positive","living_arrangements","height","uni_travel_method","uni_travel_listen","spain_budget","feel_overseas","feel_anxious","study_hrs","read_news","study_load","work","lab_zoom","social_media","gender","sleep_time","wake_time","random_number","steak_preference","dominant_hand","normal_advanced","exercise_hrs","employment_hrs","city","weekly_saving","hourly_plan","weeks_behind","assignment_on_time","used_r_before","team_role","data2x02_hrs","social_media_hrs","uni_year","sport","wam","shoe_size","decade_selection")
# overwrite the old names with the new names:
colnames(x) = new_names
# combine old and new into a data frame:
name_combo = bind_cols(New = new_names, Old = old_names)
name_combo %>% gt::gt()
```
```{r}
visdat::vis_miss(x)
```
```{r}
unique(sort(x$height))
```

```{r}
x = x %>% 
  dplyr::mutate(
    height_clean = readr::parse_number(height),
    height_clean = case_when(
      height_clean <= 2.5 ~ height_clean * 100,
      height_clean <= 9 ~ NA_real_,
      TRUE ~ height_clean
    )
  )
```

```{r}
x %>% 
  ggplot() + 
  aes(x = height_clean) + 
  geom_histogram(binwidth = 5)+ 
  labs(x = "Count", y = "Height (cm)") + 
  theme_bw()
```
```{r}
x %>% filter(height_clean > 200) %>% t()
```
# Gender

```{r}
install.packages("remotes")
remotes::install_github("ropenscilabs/gendercoder")
```
```{r}
x = x %>% mutate(
  gender_clean = gendercoder::recode_gender(gender)
)
x %>% janitor::tabyl(
  gender, gender_clean
) %>% gt::gt() %>% 
  gt::tab_spanner(label = "Recoded outcomes", columns = 2:5) %>% 
  gt::cols_label(gender = "Original outcomes")
```
# Social Media
```{r}
x %>% janitor::tabyl(social_media) %>% 
  gt::gt() %>% 
  gt::fmt_percent(columns = 3:4, decimals = 1) %>% 
  gt::cols_label(social_media = "Favourite social media platform")
```

```{r}
x= x %>% mutate(
  social_media_clean = tolower(social_media),
  social_media_clean = str_replace_all(social_media_clean, '[[:punct:]]',' '),
  social_media_clean = stringr::word(social_media_clean),
  social_media_clean = case_when(
    stringr::str_starts(social_media_clean,"ins") ~ "instagram",
    stringr::str_starts(social_media_clean,"ti") ~ "tiktok",
    stringr::str_starts(social_media_clean,"mess") ~ "facebook",
    stringr::str_starts(social_media_clean,"n") ~ "none",
    is.na(social_media_clean) ~ "none",
    TRUE ~ social_media_clean
  ),
  social_media_clean = tools::toTitleCase(social_media_clean),
  social_media_clean = forcats::fct_lump_min(social_media_clean, min = 10)
)
```

```{r}
x %>% janitor::tabyl(social_media_clean) %>% 
  arrange(desc(n)) %>% 
  gt::gt() %>% 
  gt::fmt_percent(columns = 3, decimals = 1) %>% 
  gt::cols_label(social_media_clean = "Favourite social media platform") %>% 
  gt::cols_align(align = "left", columns = 1)
```
# Sport

```{r}
x = x %>% 
  mutate(identifier = row_number()) %>% 
  mutate(sport = replace_na(sport, "I Don't Play any Sport"))
```

```{r}
sport <- x %>%
  dplyr::select(identifier, sport) %>% 
  tidyr::separate_rows(sport,
                       sep = ", ") %>% 
  dplyr::mutate(sport = tools::toTitleCase(sport),
                sport = factor(sport),
                sport = forcats::fct_lump_min(sport, 2))
```

```{r}
sport %>% ggplot() + 
  aes(y = reorder(sport, sport, function(x) length(x))) + 
  geom_bar() + 
  labs(y = "", x = "Count") + 
  theme_bw()
```
```{r}
sport_wide = sport %>% 
  mutate(value = 1) %>% 
  distinct() %>% 
  pivot_wider(id_cols = identifier,
              names_from = sport, 
              values_from = value,
              values_fill = 0)
glimpse(sport_wide)
```
```{r}
x = x %>%
  left_join(sport_wide, by = "identifier") %>% 
  janitor::clean_names()
colnames(x)
```

